(function(){var h={},mt={},c={id:"943cc4109ba97a8f352f6b733725ac91",dm:["edeng.cn"],js:"tongji.baidu.com/hm-web/js/",etrk:[],icon:'/hmt/icon/21|gif|20|20',ctrk:true,align:1,nv:-1,vdur:1800000,age:31536000000,rec:0,rp:[],trust:0,vcard:0,qiao:0,lxb:0,kbtrk:0,pt:0,aet:'',conv:0,med:0,cvcc:'',cvcf:[],apps:''};var r=void 0,s=!0,t=null,u=!1;mt.cookie={};mt.cookie.set=function(b,a,d){var k;d.Y&&(k=new Date,k.setTime(k.getTime()+d.Y));document.cookie=b+"="+a+(d.domain?"; domain="+d.domain:"")+(d.path?"; path="+d.path:"")+(k?"; expires="+k.toGMTString():"")+(d.Vb?"; secure":"")};mt.cookie.get=function(b){return(b=RegExp("(^| )"+b+"=([^;]*)(;|$)").exec(document.cookie))?b[2]:t};mt.lang={};mt.lang.d=function(b,a){return"[object "+a+"]"==={}.toString.call(b)};
mt.lang.wa=function(b){return mt.lang.d(b,"Number")&&isFinite(b)};mt.lang.ea=function(){return mt.lang.d(c.aet,"String")};mt.lang.i=function(b){return b.replace?b.replace(/'/g,"'0").replace(/\*/g,"'1").replace(/!/g,"'2"):b};mt.lang.trim=function(b){return b.replace(/^\s+|\s+$/g,"")};mt.lang.F=function(b,a){var d=u;if(b==t||!mt.lang.d(b,"Array")||a===r)return d;if(Array.prototype.indexOf)d=-1!==b.indexOf(a);else for(var k=0;k<b.length;k++)if(b[k]===a){d=s;break}return d};
(function(){var b=mt.lang;mt.e={};mt.e.Wa=function(a){return document.getElementById(a)};mt.e.ba=function(a,d){var b=[],f=[];if(!a)return f;for(;a.parentNode!=t;){for(var n=0,l=0,p=a.parentNode.childNodes.length,e=0;e<p;e++){var g=a.parentNode.childNodes[e];if(g.nodeName===a.nodeName&&(n++,g===a&&(l=n),0<l&&1<n))break}if((p=""!==a.id)&&d){b.unshift("#"+encodeURIComponent(a.id));break}else p&&(p="#"+encodeURIComponent(a.id),p=0<b.length?p+">"+b.join(">"):p,f.push(p)),b.unshift(encodeURIComponent(String(a.nodeName).toLowerCase())+
(1<n?"["+l+"]":""));a=a.parentNode}f.push(b.join(">"));return f};mt.e.ta=function(a){return(a=mt.e.ba(a,s))&&a.length?String(a[0]):""};mt.e.Sb=function(a){return mt.e.ba(a,u)};mt.e.Xa=function(a){var b;for(b="A";(a=a.parentNode)&&1==a.nodeType;)if(a.tagName==b)return a;return t};mt.e.Za=function(a){return 9===a.nodeType?a:a.ownerDocument||a.document};mt.e.eb=function(a){var b={top:0,left:0};if(!a)return b;var k=mt.e.Za(a).documentElement;"undefined"!==typeof a.getBoundingClientRect&&(b=a.getBoundingClientRect());
return{top:b.top+(window.pageYOffset||k.scrollTop)-(k.clientTop||0),left:b.left+(window.pageXOffset||k.scrollLeft)-(k.clientLeft||0)}};mt.e.getAttribute=function(a,b){var k=a.getAttribute&&a.getAttribute(b)||t;if(!k&&a.attributes&&a.attributes.length)for(var f=a.attributes,n=f.length,l=0;l<n;l++)f[l].nodeName===b&&(k=f[l].nodeValue);return k};mt.e.M=function(a){var b="document";a.tagName!==r&&(b=a.tagName);return b.toLowerCase()};mt.e.hb=function(a){var d="";a.textContent?d=b.trim(a.textContent):
a.innerText&&(d=b.trim(a.innerText));d&&(d=d.replace(/\s+/g," ").substring(0,255));return d};mt.e.$a=function(a){var b=mt.e.M(a);"input"===b&&("button"===a.type||"submit"===a.type)?a=a.value||"":"img"===b?(b=mt.e.getAttribute,a=b(a,"alt")||b(a,"title")||b(a,"src")):a="body"===b||"html"===b?["(hm-default-content-for-",b,")"].join(""):mt.e.hb(a);return String(a).substring(0,255)};(function(){(mt.e.Ab=function(){function a(){if(!a.O){a.O=s;for(var b=0,d=f.length;b<d;b++)f[b]()}}function b(){try{document.documentElement.doScroll("left")}catch(k){setTimeout(b,
1);return}a()}var k=u,f=[],n;document.addEventListener?n=function(){document.removeEventListener("DOMContentLoaded",n,u);a()}:document.attachEvent&&(n=function(){"complete"===document.readyState&&(document.detachEvent("onreadystatechange",n),a())});(function(){if(!k)if(k=s,"complete"===document.readyState)a.O=s;else if(document.addEventListener)document.addEventListener("DOMContentLoaded",n,u),window.addEventListener("load",a,u);else if(document.attachEvent){document.attachEvent("onreadystatechange",
n);window.attachEvent("onload",a);var f=u;try{f=window.frameElement==t}catch(p){}document.documentElement.doScroll&&f&&b()}})();return function(b){a.O?b():f.push(b)}}()).O=u})();return mt.e})();mt.event={};mt.event.c=function(b,a,d){b.attachEvent?b.attachEvent("on"+a,function(a){d.call(b,a)}):b.addEventListener&&b.addEventListener(a,d,u)};mt.event.preventDefault=function(b){b.preventDefault?b.preventDefault():b.returnValue=u};
(function(){var b=mt.event;mt.g={};mt.g.da=/msie (\d+\.\d+)/i.test(navigator.userAgent);mt.g.tb=/msie (\d+\.\d+)/i.test(navigator.userAgent)?document.documentMode||+RegExp.$1:r;mt.g.cookieEnabled=navigator.cookieEnabled;mt.g.javaEnabled=navigator.javaEnabled();mt.g.language=navigator.language||navigator.browserLanguage||navigator.systemLanguage||navigator.userLanguage||"";mt.g.Cb=(window.screen.width||0)+"x"+(window.screen.height||0);mt.g.colorDepth=window.screen.colorDepth||0;mt.g.D=function(){var a;
a=a||document;return parseInt(window.pageYOffset||a.documentElement.scrollTop||a.body&&a.body.scrollTop||0,10)};mt.g.z=function(){var a=document;return parseInt(window.innerHeight||a.documentElement.clientHeight||a.body&&a.body.clientHeight||0,10)};mt.g.orientation=0;(function(){function a(){var a=0;window.orientation!==r&&(a=window.orientation);screen&&(screen.orientation&&screen.orientation.angle!==r)&&(a=screen.orientation.angle);mt.g.orientation=a}a();b.c(window,"orientationchange",a)})();return mt.g})();
mt.m={};mt.m.parse=function(){return(new Function('return (" + source + ")'))()};
mt.m.stringify=function(){function b(a){/["\\\x00-\x1f]/.test(a)&&(a=a.replace(/["\\\x00-\x1f]/g,function(a){var b=d[a];if(b)return b;b=a.charCodeAt();return"\\u00"+Math.floor(b/16).toString(16)+(b%16).toString(16)}));return'"'+a+'"'}function a(a){return 10>a?"0"+a:a}var d={"\b":"\\b","\t":"\\t","\n":"\\n","\f":"\\f","\r":"\\r",'"':'\\"',"\\":"\\\\"};return function(d){switch(typeof d){case "undefined":return"undefined";case "number":return isFinite(d)?String(d):"null";case "string":return b(d);case "boolean":return String(d);
default:if(d===t)return"null";if(d instanceof Array){var f=["["],n=d.length,l,p,e;for(p=0;p<n;p++)switch(e=d[p],typeof e){case "undefined":case "function":case "unknown":break;default:l&&f.push(","),f.push(mt.m.stringify(e)),l=1}f.push("]");return f.join("")}if(d instanceof Date)return'"'+d.getFullYear()+"-"+a(d.getMonth()+1)+"-"+a(d.getDate())+"T"+a(d.getHours())+":"+a(d.getMinutes())+":"+a(d.getSeconds())+'"';l=["{"];p=mt.m.stringify;for(n in d)if(Object.prototype.hasOwnProperty.call(d,n))switch(e=
d[n],typeof e){case "undefined":case "unknown":case "function":break;default:f&&l.push(","),f=1,l.push(p(n)+":"+p(e))}l.push("}");return l.join("")}}}();mt.localStorage={};mt.localStorage.T=function(){if(!mt.localStorage.j)try{mt.localStorage.j=document.createElement("input"),mt.localStorage.j.type="hidden",mt.localStorage.j.style.display="none",mt.localStorage.j.addBehavior("#default#userData"),document.getElementsByTagName("head")[0].appendChild(mt.localStorage.j)}catch(b){return u}return s};
mt.localStorage.set=function(b,a,d){var k=new Date;k.setTime(k.getTime()+d||31536E6);try{window.localStorage?(a=k.getTime()+"|"+a,window.localStorage.setItem(b,a)):mt.localStorage.T()&&(mt.localStorage.j.expires=k.toUTCString(),mt.localStorage.j.load(document.location.hostname),mt.localStorage.j.setAttribute(b,a),mt.localStorage.j.save(document.location.hostname))}catch(f){}};
mt.localStorage.get=function(b){if(window.localStorage){if(b=window.localStorage.getItem(b)){var a=b.indexOf("|"),d=b.substring(0,a)-0;if(d&&d>(new Date).getTime())return b.substring(a+1)}}else if(mt.localStorage.T())try{return mt.localStorage.j.load(document.location.hostname),mt.localStorage.j.getAttribute(b)}catch(k){}return t};
mt.localStorage.remove=function(b){if(window.localStorage)window.localStorage.removeItem(b);else if(mt.localStorage.T())try{mt.localStorage.j.load(document.location.hostname),mt.localStorage.j.removeAttribute(b),mt.localStorage.j.save(document.location.hostname)}catch(a){}};mt.sessionStorage={};mt.sessionStorage.set=function(b,a){if(window.sessionStorage)try{window.sessionStorage.setItem(b,a)}catch(d){}};
mt.sessionStorage.get=function(b){return window.sessionStorage?window.sessionStorage.getItem(b):t};mt.sessionStorage.remove=function(b){window.sessionStorage&&window.sessionStorage.removeItem(b)};mt.Aa={};mt.Aa.log=function(b,a){var d=new Image,k="mini_tangram_log_"+Math.floor(2147483648*Math.random()).toString(36);window[k]=d;d.onload=d.onerror=d.onabort=function(){d.onload=d.onerror=d.onabort=t;d=window[k]=t;a&&a(b)};d.src=b};mt.la={};
mt.la.ib=function(){var b="";if(navigator.plugins&&navigator.mimeTypes.length){var a=navigator.plugins["Shockwave Flash"];a&&a.description&&(b=a.description.replace(/^.*\s+(\S+)\s+\S+$/,"$1"))}else if(window.ActiveXObject)try{if(a=new ActiveXObject("ShockwaveFlash.ShockwaveFlash"))(b=a.GetVariable("$version"))&&(b=b.replace(/^.*\s+(\d+),(\d+).*$/,"$1.$2"))}catch(d){}return b};
mt.la.Rb=function(b,a,d,k,f){return'<object classid="clsid:d27cdb6e-ae6d-11cf-96b8-444553540000" id="'+b+'" width="'+d+'" height="'+k+'"><param name="movie" value="'+a+'" /><param name="flashvars" value="'+(f||"")+'" /><param name="allowscriptaccess" value="always" /><embed type="application/x-shockwave-flash" name="'+b+'" width="'+d+'" height="'+k+'" src="'+a+'" flashvars="'+(f||"")+'" allowscriptaccess="always" /></object>'};mt.url={};
mt.url.k=function(b,a){var d=b.match(RegExp("(^|&|\\?|#)("+a+")=([^&#]*)(&|$|#)",""));return d?d[3]:t};mt.url.Tb=function(b){return(b=b.match(/^(https?:)\/\//))?b[1]:t};mt.url.bb=function(b){return(b=b.match(/^(https?:\/\/)?([^\/\?#]*)/))?b[2].replace(/.*@/,""):t};mt.url.aa=function(b){return(b=mt.url.bb(b))?b.replace(/:\d+$/,""):b};mt.url.ba=function(b){return(b=b.match(/^(https?:\/\/)?[^\/]*(.*)/))?b[2].replace(/[\?#].*/,"").replace(/^$/,"/"):t};
(function(){function b(){for(var a=u,b=document.getElementsByTagName("script"),k=b.length,k=100<k?100:k,f=0;f<k;f++){var n=b[f].src;if(n&&0===n.indexOf("https://hm.baidu.com/h")){a=s;break}}return a}return h.Va=b})();var A=h.Va;
h.l={rb:"http://tongji.baidu.com/hm-web/welcome/ico",ia:"hm.baidu.com/hm.gif",Ha:"tongji.baidu.com",ob:"hmmd",pb:"hmpl",Nb:"utm_medium",nb:"hmkw",Pb:"utm_term",lb:"hmci",Mb:"utm_content",qb:"hmsr",Ob:"utm_source",mb:"hmcu",Lb:"utm_campaign",A:0,o:Math.round(+new Date/1E3),C:Math.round(+new Date/1E3)%65535,protocol:"https:"===document.location.protocol?"https:":"http:",P:A()||"https:"===document.location.protocol?"https:":"http:",Ub:0,Na:6E5,vb:6E5,Db:5E3,Oa:5,B:1024,Ma:1,I:2147483647,Ba:"kb cc cf ci ck cl cm cp cu cw ds vl ep et fl ja ln lo lt rnd si su v cv lv api sn ct u tt".split(" "),
G:s,qa:["a","input","button"],Ja:{id:"data-hm-id",W:"data-hm-class",na:"data-hm-xpath",content:"data-hm-content",S:"data-hm-tag",link:"data-hm-link"},pa:"data-hm-enabled",oa:"data-hm-disabled"};(function(){var b={s:{},c:function(a,b){this.s[a]=this.s[a]||[];this.s[a].push(b)},L:function(a,b){this.s[a]=this.s[a]||[];for(var k=this.s[a].length,f=0;f<k;f++)this.s[a][f](b)}};return h.r=b})();
(function(){function b(b,k){var f=document.createElement("script");f.charset="utf-8";a.d(k,"Function")&&(f.readyState?f.onreadystatechange=function(){if("loaded"===f.readyState||"complete"===f.readyState)f.onreadystatechange=t,k()}:f.onload=function(){k()});f.src=b;var n=document.getElementsByTagName("script")[0];n.parentNode.insertBefore(f,n)}var a=mt.lang;return h.load=b})();
(function(){var b=h.l,a={init:function(){if(""!==c.icon){var a=c.icon.split("|"),k=b.rb+"?s="+c.id,f="https://hmcdn.baidu.com/static"+a[0]+".gif";document.write("swf"===a[1]||"gif"===a[1]?'<a href="'+k+'" target="_blank"><img border="0" src="'+f+'" width="'+a[2]+'" height="'+a[3]+'"></a>':'<a href="'+k+'" target="_blank">'+a[0]+"</a>")}}};h.r.c("pv-b",a.init);return a})();
(function(){var b=mt.e,a=mt.lang,d=mt.event,k=mt.g,f=h.l,n=h.r,l=[],p={Ca:function(){c.ctrk&&(d.c(document,"mouseup",p.La()),d.c(window,"unload",function(){p.Q()}),setInterval(function(){p.Q()},f.Na))},La:function(){return function(g){g=p.Ya(g);if(""!==g){var a=(f.P+"//"+f.ia+"?"+h.a.za().replace(/ep=[^&]*/,"ep="+encodeURIComponent(g))).length;a+(f.I+"").length>f.B||(a+encodeURIComponent(l.join("!")+(l.length?"!":"")).length+(f.I+"").length>f.B&&p.Q(),l.push(g),(l.length>=f.Oa||/\*a\*/.test(g))&&
p.Q())}}},Ya:function(g){var d=g.target||g.srcElement;if(0===f.Ma){var m=(d.tagName||"").toLowerCase();if("embed"==m||"object"==m)return""}var q;k.da?(q=Math.max(document.documentElement.scrollTop,document.body.scrollTop),m=Math.max(document.documentElement.scrollLeft,document.body.scrollLeft),m=g.clientX+m,q=g.clientY+q):(m=g.pageX,q=g.pageY);g=p.cb(g,d,m,q);var e=window.innerWidth||document.documentElement.clientWidth||document.body.offsetWidth;switch(c.align){case 1:m-=e/2;break;case 2:m-=e}e=
[];e.push(m);e.push(q);e.push(g.wb);e.push(g.xb);e.push(g.zb);e.push(a.i(g.yb));e.push(g.Qb);e.push(g.jb);(d="a"===(d.tagName||"").toLowerCase()?d:b.Xa(d))?(e.push("a"),e.push(a.i(encodeURIComponent(d.href)))):e.push("b");return e.join("*")},cb:function(g,d,m,q){g=b.ta(d);var e=0,f=0,n=0,l=0;if(d&&(e=d.offsetWidth||d.clientWidth,f=d.offsetHeight||d.clientHeight,l=b.eb(d),n=l.left,l=l.top,a.d(d.getBBox,"Function")&&(f=d.getBBox(),e=f.width,f=f.height),"html"===(d.tagName||"").toLowerCase()))e=Math.max(e,
d.clientWidth),f=Math.max(f,d.clientHeight);return{wb:Math.round(100*((m-n)/e)),xb:Math.round(100*((q-l)/f)),zb:k.orientation,yb:g,Qb:e,jb:f}},Q:function(){0!==l.length&&(h.a.b.et=2,h.a.b.ep=l.join("!"),h.a.h(),l=[])}},e={Fa:function(){c.ctrk&&setInterval(e.Eb,f.Db)},Eb:function(){var g=k.D()+k.z();0<g-h.a.b.vl&&(h.a.b.vl=g)}};n.c("pv-b",p.Ca);n.c("pv-b",e.Fa);return p})();
(function(){var b=mt.lang,a=mt.e,d=mt.event,k=mt.g,f=h.l,n=h.r,l=+new Date,p=[],e={ra:function(){return function(g){if(h.a&&h.a.G&&c.aet&&c.aet.length){var d=g.target||g.srcElement;if(d){var m=h.a.qa,q=a.getAttribute(d,f.pa)!=t?s:u;if(a.getAttribute(d,f.oa)==t)if(q)e.U(e.$(d,g));else{var k=a.M(d);if(b.F(m,"*")||b.F(m,k))e.U(e.$(d,g));else for(;d.parentNode!=t;){var q=d.parentNode,k=a.M(q),n="a"===k&&b.F(m,"a")?s:u,k="button"===k&&b.F(m,"button")?s:u,l=a.getAttribute(q,f.pa)!=t?s:u;if(a.getAttribute(q,
f.oa)==t&&(n||k||l)){e.U(e.$(q,g));break}d=d.parentNode}}}}}},$:function(g,d){var m={},q=f.Ja;m.id=a.getAttribute(g,q.id)||a.getAttribute(g,"id")||"";m.W=a.getAttribute(g,q.W)||a.getAttribute(g,"class")||"";m.na=a.getAttribute(g,q.na)||a.ta(g);m.content=a.getAttribute(g,q.content)||a.$a(g);m.S=a.getAttribute(g,q.S)||a.M(g);m.link=a.getAttribute(g,q.link)||a.getAttribute(g,"href")||"";m.type=d.type||"click";q=b.wa(g.offsetTop)?g.offsetTop:0;"click"===d.type?q=k.da?d.clientY+Math.max(document.documentElement.scrollTop,
document.body.scrollTop):d.pageY:"touchend"===d.type&&(d.ga&&b.d(d.ga.changedTouches,"Array")&&d.ga.changedTouches.length)&&(q=d.ga.changedTouches[0].pageY);m.Kb=q;return m},U:function(g){var a=b.i,a=[+new Date-(h.a.w!==r?h.a.w:l),a(g.id),a(g.W),a(g.S),a(g.na),a(g.link),a(g.content),g.type,g.Kb].join("*");e.V(a);b.F(["a"],g.S)&&b.d(this.J(),"Function")&&this.J()()},V:function(g){g.length>f.B||(encodeURIComponent(p.join("!")+g).length>f.B&&(e.K(p.join("!")),p=[]),p.push(g))},K:function(g){h.a.b.et=
5;h.a.b.ep=g;h.a.h()},J:function(){return function(){p&&p.length&&(e.K(p.join("!")),p=[])}}};b.ea()&&""!==c.aet&&n.c("pv-b",function(){d.c(document,"click",e.ra());"ontouchend"in document&&d.c(window,"touchend",e.ra());d.c(window,"unload",e.J())});return e})();
(function(){var b=mt.event,a=mt.g,d=h.l,k=h.r,f=+new Date,n=[],l=t,p={Ra:function(){return function(){h.a&&(h.a.G&&c.aet&&c.aet.length)&&(window.clearTimeout(l),l=window.setTimeout(function(){p.Ea(a.D()+a.z())},150))}},Ea:function(a){p.V([+new Date-(h.a.w!==r?h.a.w:f),a].join("*"))},V:function(a){if(encodeURIComponent(n.join("!")+a).length>d.B||5<n.length)p.K(n.join("!")),n=[];n.push(a)},K:function(b){h.a.b.et=6;h.a.b.vh=a.z();h.a.b.ep=b;h.a.h()},J:function(){return function(){n&&n.length&&(p.K(n.join("!")),
n=[])}}};mt.lang.ea()&&""!==c.aet&&k.c("pv-b",function(){b.c(window,"scroll",p.Ra());b.c(window,"unload",p.J())});return p})();
(function(){function b(){return function(){h.a.b.nv=0;h.a.b.st=4;h.a.b.et=3;h.a.b.ep=h.X.fb()+","+h.X.ab();h.a.h()}}function a(){clearTimeout(z);var b;w&&(b="visible"==document[w]);y&&(b=!document[y]);p="undefined"==typeof b?s:b;if((!l||!e)&&p&&g)x=s,m=+new Date;else if(l&&e&&(!p||!g))x=u,q+=+new Date-m;l=p;e=g;z=setTimeout(a,100)}function d(a){var g=document,b="";if(a in g)b=a;else for(var m=["webkit","ms","moz","o"],d=0;d<m.length;d++){var q=m[d]+a.charAt(0).toUpperCase()+a.slice(1);if(q in g){b=
q;break}}return b}function k(b){if(!("focus"==b.type||"blur"==b.type)||!(b.target&&b.target!=window))g="focus"==b.type||"focusin"==b.type?s:u,a()}var f=mt.event,n=h.r,l=s,p=s,e=s,g=s,v=+new Date,m=v,q=0,x=s,w=d("visibilityState"),y=d("hidden"),z;a();(function(){var g=w.replace(/[vV]isibilityState/,"visibilitychange");f.c(document,g,a);f.c(window,"pageshow",a);f.c(window,"pagehide",a);"object"==typeof document.onfocusin?(f.c(document,"focusin",k),f.c(document,"focusout",k)):(f.c(window,"focus",k),
f.c(window,"blur",k))})();h.X={fb:function(){return+new Date-v},ab:function(){return x?+new Date-m+q:q}};n.c("pv-b",function(){f.c(window,"unload",b())});return h.X})();
(function(){var b=mt.lang,a=h.l,d=h.load,k={ub:function(f){if((window._dxt===r||b.d(window._dxt,"Array"))&&"undefined"!==typeof h.a){var k=h.a.Z();d([a.protocol,"//datax.baidu.com/x.js?si=",c.id,"&dm=",encodeURIComponent(k)].join(""),f)}},Jb:function(a){if(b.d(a,"String")||b.d(a,"Number"))window._dxt=window._dxt||[],window._dxt.push(["_setUserId",a])}};return h.Pa=k})();
(function(){function b(a,b,m,d){if(!(a===r||b===r||d===r)){if(""===a)return[b,m,d].join("*");a=String(a).split("!");for(var e,f=u,k=0;k<a.length;k++)if(e=a[k].split("*"),String(b)===e[0]){e[1]=m;e[2]=d;a[k]=e.join("*");f=s;break}f||a.push([b,m,d].join("*"));return a.join("!")}}function a(g){for(var b in g)if({}.hasOwnProperty.call(g,b)){var m=g[b];d.d(m,"Object")||d.d(m,"Array")?a(m):g[b]=String(m)}}var d=mt.lang,k=mt.m,f=mt.g,n=h.l,l=h.r,p=h.Pa,e={H:[],R:0,xa:u,p:{ma:"",page:""},init:function(){e.f=
0;l.c("pv-b",function(){e.Qa();e.Ta()});l.c("pv-d",function(){e.Ua();e.p.page=""});l.c("stag-b",function(){h.a.b.api=e.f||e.R?e.f+"_"+e.R:"";h.a.b.ct=[decodeURIComponent(h.a.getData("Hm_ct_"+c.id)||""),e.p.ma,e.p.page].join("!")});l.c("stag-d",function(){h.a.b.api=0;e.f=0;e.R=0})},Qa:function(){var a=window._hmt||[];if(!a||d.d(a,"Array"))window._hmt={id:c.id,cmd:{},push:function(){for(var a=window._hmt,g=0;g<arguments.length;g++){var b=arguments[g];d.d(b,"Array")&&(a.cmd[a.id].push(b),"_setAccount"===
b[0]&&(1<b.length&&/^[0-9a-f]{32}$/.test(b[1]))&&(b=b[1],a.id=b,a.cmd[b]=a.cmd[b]||[]))}}},window._hmt.cmd[c.id]=[],window._hmt.push.apply(window._hmt,a)},Ta:function(){var a=window._hmt;if(a&&a.cmd&&a.cmd[c.id])for(var b=a.cmd[c.id],d=/^_track(Event|MobConv|Order|RTEvent)$/,q=0,f=b.length;q<f;q++){var k=b[q];d.test(k[0])?e.H.push(k):e.ha(k)}a.cmd[c.id]={push:e.ha}},Ua:function(){if(0<e.H.length)for(var a=0,b=e.H.length;a<b;a++)e.ha(e.H[a]);e.H=t},ha:function(a){var b=a[0];if(e.hasOwnProperty(b)&&
d.d(e[b],"Function"))e[b](a)},_setAccount:function(a){1<a.length&&/^[0-9a-f]{32}$/.test(a[1])&&(e.f|=1)},_setAutoPageview:function(a){if(1<a.length&&(a=a[1],u===a||s===a))e.f|=2,h.a.ua=a},_trackPageview:function(a){if(1<a.length&&a[1].charAt&&"/"===a[1].charAt(0)){e.f|=4;h.a.b.et=0;h.a.b.ep="";h.a.b.vl=f.D()+f.z();h.a.b.kb=0;h.a.ca?(h.a.b.nv=0,h.a.b.st=4):h.a.ca=s;var b=h.a.b.u,d=h.a.b.su;h.a.b.u=n.protocol+"//"+document.location.host+a[1];e.xa||(h.a.b.su=document.location.href);h.a.h();h.a.b.u=b;
h.a.b.su=d;h.a.w=+new Date}},_trackEvent:function(a){2<a.length&&(e.f|=8,h.a.b.nv=0,h.a.b.st=4,h.a.b.et=4,h.a.b.ep=d.i(a[1])+"*"+d.i(a[2])+(a[3]?"*"+d.i(a[3]):"")+(a[4]?"*"+d.i(a[4]):""),h.a.h())},_setCustomVar:function(a){if(!(4>a.length)){var b=a[1],m=a[4]||3;if(0<b&&6>b&&0<m&&4>m){e.R++;for(var q=(h.a.b.cv||"*").split("!"),f=q.length;f<b-1;f++)q.push("*");q[b-1]=m+"*"+d.i(a[2])+"*"+d.i(a[3]);h.a.b.cv=q.join("!");a=h.a.b.cv.replace(/[^1](\*[^!]*){2}/g,"*").replace(/((^|!)\*)+$/g,"");""!==a?h.a.setData("Hm_cv_"+
c.id,encodeURIComponent(a),c.age):h.a.Bb("Hm_cv_"+c.id)}}},_setUserTag:function(a){if(!(3>a.length)){var e=d.i(a[1]);a=d.i(a[2]);if(e!==r&&a!==r){var m=decodeURIComponent(h.a.getData("Hm_ct_"+c.id)||""),m=b(m,e,1,a);h.a.setData("Hm_ct_"+c.id,encodeURIComponent(m),c.age)}}},_setVisitTag:function(a){if(!(3>a.length)){var f=d.i(a[1]);a=d.i(a[2]);if(f!==r&&a!==r){var m=e.p.ma,m=b(m,f,2,a);e.p.ma=m}}},_setPageTag:function(a){if(!(3>a.length)){var f=d.i(a[1]);a=d.i(a[2]);if(f!==r&&a!==r){var m=e.p.page,
m=b(m,f,3,a);e.p.page=m}}},_setReferrerOverride:function(a){1<a.length&&(h.a.b.su=a[1].charAt&&"/"===a[1].charAt(0)?n.protocol+"//"+window.location.host+a[1]:a[1],e.xa=s)},_trackOrder:function(b){b=b[1];d.d(b,"Object")&&(a(b),e.f|=16,h.a.b.nv=0,h.a.b.st=4,h.a.b.et=94,h.a.b.ep=k.stringify(b),h.a.h())},_trackMobConv:function(a){if(a={webim:1,tel:2,map:3,sms:4,callback:5,share:6}[a[1]])e.f|=32,h.a.b.et=93,h.a.b.ep=a,h.a.h()},_trackRTPageview:function(b){b=b[1];d.d(b,"Object")&&(a(b),b=k.stringify(b),
512>=encodeURIComponent(b).length&&(e.f|=64,h.a.b.rt=b))},_trackRTEvent:function(b){b=b[1];if(d.d(b,"Object")){a(b);b=encodeURIComponent(k.stringify(b));var f=function(a){var b=h.a.b.rt;e.f|=128;h.a.b.et=90;h.a.b.rt=a;h.a.h();h.a.b.rt=b},m=b.length;if(900>=m)f.call(this,b);else for(var m=Math.ceil(m/900),q="block|"+Math.round(Math.random()*n.I).toString(16)+"|"+m+"|",l=[],w=0;w<m;w++)l.push(w),l.push(b.substring(900*w,900*w+900)),f.call(this,q+l.join("|")),l=[]}},_setUserId:function(a){a=a[1];p.ub();
p.Jb(a)},_setAutoTracking:function(a){if(1<a.length&&(a=a[1],u===a||s===a))h.a.va=a},_setAutoEventTracking:function(a){if(1<a.length&&(a=a[1],u===a||s===a))h.a.G=a}};e.init();h.Ia=e;return h.Ia})();
(function(){function b(){"undefined"===typeof window["_bdhm_loaded_"+c.id]&&(window["_bdhm_loaded_"+c.id]=s,this.b={},this.va=this.ua=s,this.G=g.G,this.qa=f.ea()&&0<c.aet.length?c.aet.split(","):"",this.ca=u,this.init())}var a=mt.url,d=mt.Aa,k=mt.la,f=mt.lang,n=mt.cookie,l=mt.g,p=mt.localStorage,e=mt.sessionStorage,g=h.l,v=h.r;b.prototype={fa:function(a,b){a="."+a.replace(/:\d+/,"");b="."+b.replace(/:\d+/,"");var d=a.indexOf(b);return-1<d&&d+b.length===a.length},ya:function(a,b){a=a.replace(/^https?:\/\//,
"");return 0===a.indexOf(b)},N:function(b){for(var d=0;d<c.dm.length;d++)if(-1<c.dm[d].indexOf("/")){if(this.ya(b,c.dm[d]))return s}else{var g=a.aa(b);if(g&&this.fa(g,c.dm[d]))return s}return u},Z:function(){for(var a=document.location.hostname,b=0,d=c.dm.length;b<d;b++)if(this.fa(a,c.dm[b]))return c.dm[b].replace(/(:\d+)?[\/\?#].*/,"");return a},sa:function(){for(var a=0,b=c.dm.length;a<b;a++){var d=c.dm[a];if(-1<d.indexOf("/")&&this.ya(document.location.href,d))return d.replace(/^[^\/]+(\/.*)/,
"$1")+"/"}return"/"},gb:function(){if(!document.referrer)return g.o-g.A>c.vdur?1:4;var b=u;this.N(document.referrer)&&this.N(document.location.href)?b=s:(b=a.aa(document.referrer),b=this.fa(b||"",document.location.hostname));return b?g.o-g.A>c.vdur?1:4:3},getData:function(a){try{return n.get(a)||e.get(a)||p.get(a)}catch(b){}},setData:function(a,b,d){try{n.set(a,b,{domain:this.Z(),path:this.sa(),Y:d}),d?p.set(a,b,d):e.set(a,b)}catch(g){}},Bb:function(a){try{n.set(a,"",{domain:this.Z(),path:this.sa(),
Y:-1}),e.remove(a),p.remove(a)}catch(b){}},Hb:function(){var a,b,d,e,f;g.A=this.getData("Hm_lpvt_"+c.id)||0;13===g.A.length&&(g.A=Math.round(g.A/1E3));b=this.gb();a=4!==b?1:0;if(d=this.getData("Hm_lvt_"+c.id)){e=d.split(",");for(f=e.length-1;0<=f;f--)13===e[f].length&&(e[f]=""+Math.round(e[f]/1E3));for(;2592E3<g.o-e[0];)e.shift();f=4>e.length?2:3;for(1===a&&e.push(g.o);4<e.length;)e.shift();d=e.join(",");e=e[e.length-1]}else d=g.o,e="",f=1;this.setData("Hm_lvt_"+c.id,d,c.age);this.setData("Hm_lpvt_"+
c.id,g.o);d=g.o===this.getData("Hm_lpvt_"+c.id)?"1":"0";if(0===c.nv&&this.N(document.location.href)&&(""===document.referrer||this.N(document.referrer)))a=0,b=4;this.b.nv=a;this.b.st=b;this.b.cc=d;this.b.lt=e;this.b.lv=f},za:function(){for(var a=[],b=this.b.et,d=+new Date,e=0,f=g.Ba.length;e<f;e++){var k=g.Ba[e],l=this.b[k];"undefined"!==typeof l&&""!==l&&("tt"!==k||"tt"===k&&0===b)&&(("ct"!==k||"ct"===k&&0===b)&&("kb"!==k||"kb"===k&&3===b))&&a.push(k+"="+encodeURIComponent(l))}switch(b){case 0:a.push("sn="+
g.C);this.b.rt&&a.push("rt="+encodeURIComponent(this.b.rt));break;case 3:a.push("sn="+g.C);break;case 5:a.push("sn="+g.C);a.push("_lpt="+this.w);a.push("_ct="+d);break;case 6:a.push("sn="+g.C);a.push("_lpt="+this.w);a.push("_ct="+d);break;case 85:a.push("sn="+g.C);break;case 90:this.b.rt&&a.push("rt="+this.b.rt)}return a.join("&")},Ib:function(){this.Hb();this.b.si=c.id;this.b.su=document.referrer;this.b.ds=l.Cb;this.b.cl=l.colorDepth+"-bit";this.b.ln=String(l.language).toLowerCase();this.b.ja=l.javaEnabled?
1:0;this.b.ck=l.cookieEnabled?1:0;this.b.lo="number"===typeof _bdhm_top?1:0;this.b.fl=k.ib();this.b.v="1.2.38";this.b.cv=decodeURIComponent(this.getData("Hm_cv_"+c.id)||"");this.b.tt=document.title||"";this.b.vl=l.D()+l.z();var b=document.location.href;this.b.cm=a.k(b,g.ob)||"";this.b.cp=a.k(b,g.pb)||a.k(b,g.Nb)||"";this.b.cw=a.k(b,g.nb)||a.k(b,g.Pb)||"";this.b.ci=a.k(b,g.lb)||a.k(b,g.Mb)||"";this.b.cf=a.k(b,g.qb)||a.k(b,g.Ob)||"";this.b.cu=a.k(b,g.mb)||a.k(b,g.Lb)||""},init:function(){try{this.Ib(),
0===this.b.nv?this.Gb():this.ka(".*"),h.a=this,this.Ka(),v.L("pv-b"),this.Fb()}catch(a){var b=[];b.push("si="+c.id);b.push("n="+encodeURIComponent(a.name));b.push("m="+encodeURIComponent(a.message));b.push("r="+encodeURIComponent(document.referrer));d.log(g.P+"//"+g.ia+"?"+b.join("&"))}},Fb:function(){function a(){v.L("pv-d")}this.ua?(this.ca=s,this.b.et=0,this.b.ep="",this.b.vl=l.D()+l.z(),this.h(a)):a();this.w=+new Date},h:function(a){if(this.va){var b=this;b.b.rnd=Math.round(Math.random()*g.I);
v.L("stag-b");var e=g.P+"//"+g.ia+"?"+b.za();v.L("stag-d");b.Ga(e);d.log(e,function(d){b.ka(d);f.d(a,"Function")&&a.call(b)})}},Ka:function(){var b=document.location.hash.substring(1),d=RegExp(c.id),e=a.aa(document.referrer)===g.Ha?1:0,f=a.k(b,"jn"),k=/^heatlink$|^select$|^pageclick$/.test(f);b&&(d.test(b)&&e&&k)&&(this.b.rnd=Math.round(Math.random()*g.I),b=document.createElement("script"),b.setAttribute("type","text/javascript"),b.setAttribute("charset","utf-8"),b.setAttribute("src",g.protocol+"//"+
c.js+f+".js?"+this.b.rnd),f=document.getElementsByTagName("script")[0],f.parentNode.insertBefore(b,f))},Ga:function(a){var b=e.get("Hm_unsent_"+c.id)||"",d=this.b.u?"":"&u="+encodeURIComponent(document.location.href),b=encodeURIComponent(a.replace(/^https?:\/\//,"")+d)+(b?","+b:"");e.set("Hm_unsent_"+c.id,b)},ka:function(a){var b=e.get("Hm_unsent_"+c.id)||"";b&&(a=encodeURIComponent(a.replace(/^https?:\/\//,"")),a=RegExp(a.replace(/([\*\(\)])/g,"\\$1")+"(%26u%3D[^,]*)?,?","g"),(b=b.replace(a,"").replace(/,$/,
""))?e.set("Hm_unsent_"+c.id,b):e.remove("Hm_unsent_"+c.id))},Gb:function(){var a=this,b=e.get("Hm_unsent_"+c.id);if(b)for(var b=b.split(","),f=function(b){d.log(g.P+"//"+decodeURIComponent(b),function(b){a.ka(b)})},k=0,l=b.length;k<l;k++)f(b[k])}};return new b})();
(function(){var b=mt.event,a=mt.lang,d=h.l;if(c.kbtrk&&"undefined"!==typeof h.a){h.a.b.kb=a.wa(h.a.b.kb)?h.a.b.kb:0;var k=function(){h.a.b.et=85;h.a.b.ep=h.a.b.kb;h.a.h()};b.c(document,"keyup",function(){h.a.b.kb++});b.c(window,"unload",function(){k()});setInterval(k,d.vb)}})();var B=h.l,C=h.load;c.pt&&C([B.protocol,"//ada.baidu.com/phone-tracker/insert_bdtj?sid=",c.pt].join(""));
(function(){var b=mt.event,a=mt.m;try{if(window.performance&&performance.timing&&"undefined"!==typeof h.a){var d=function(a){var b=performance.timing,d=b[a+"Start"]?b[a+"Start"]:0;a=b[a+"End"]?b[a+"End"]:0;return{start:d,end:a,value:0<a-d?a-d:0}},k=function(){var b;b=d("navigation");var f=d("request");b={netAll:f.start-b.start,netDns:d("domainLookup").value,netTcp:d("connect").value,srv:d("response").start-f.start,dom:performance.timing.domInteractive-performance.timing.fetchStart,loadEvent:d("loadEvent").end-
b.start};h.a.b.et=87;h.a.b.ep=a.stringify(b);h.a.h()};b.c(window,"load",function(){setTimeout(k,500)})}}catch(f){}})();
(function(){var b=mt.g,a=mt.lang,d=mt.event,k=mt.m;if("undefined"!==typeof h.a&&(c.med||(!b.da||7<b.tb)&&c.cvcc)){var f,n,l,p,e=function(a){if(a.item){for(var b=a.length,d=Array(b);b--;)d[b]=a[b];return d}return[].slice.call(a)},g=function(a,b){for(var d in a)if(a.hasOwnProperty(d)&&b.call(a,d,a[d])===u)return u},v=function(b,d){var e={};e.n=f;e.t="clk";e.v=b;if(d){var g=d.getAttribute("href"),m=d.getAttribute("onclick")?""+d.getAttribute("onclick"):t,n=d.getAttribute("id")||"";l.test(g)?(e.sn="mediate",
e.snv=g):a.d(m,"String")&&l.test(m)&&(e.sn="wrap",e.snv=m);e.id=n}h.a.b.et=86;h.a.b.ep=k.stringify(e);h.a.h();for(e=+new Date;400>=+new Date-e;);};if(c.med)n="/zoosnet",f="swt",l=/swt|zixun|call|chat|zoos|business|talk|kefu|openkf|online|\/LR\/Chatpre\.aspx/i,p={click:function(){for(var a=[],b=e(document.getElementsByTagName("a")),b=[].concat.apply(b,e(document.getElementsByTagName("area"))),b=[].concat.apply(b,e(document.getElementsByTagName("img"))),d,f,g=0,k=b.length;g<k;g++)d=b[g],f=d.getAttribute("onclick"),
d=d.getAttribute("href"),(l.test(f)||l.test(d))&&a.push(b[g]);return a}};else if(c.cvcc){n="/other-comm";f="other";l=c.cvcc.q||r;var m=c.cvcc.id||r;p={click:function(){for(var a=[],b=e(document.getElementsByTagName("a")),b=[].concat.apply(b,e(document.getElementsByTagName("area"))),b=[].concat.apply(b,e(document.getElementsByTagName("img"))),d,f,g,k=0,n=b.length;k<n;k++)d=b[k],l!==r?(f=d.getAttribute("onclick"),g=d.getAttribute("href"),m?(d=d.getAttribute("id"),(l.test(f)||l.test(g)||m.test(d))&&
a.push(b[k])):(l.test(f)||l.test(g))&&a.push(b[k])):m!==r&&(d=d.getAttribute("id"),m.test(d)&&a.push(b[k]));return a}}}if("undefined"!==typeof p&&"undefined"!==typeof l){var q;n+=/\/$/.test(n)?"":"/";var x=function(b,d){if(q===d)return v(n+b,d),u;if(a.d(d,"Array")||a.d(d,"NodeList"))for(var e=0,f=d.length;e<f;e++)if(q===d[e])return v(n+b+"/"+(e+1),d[e]),u};d.c(document,"mousedown",function(b){b=b||window.event;q=b.target||b.srcElement;var d={};for(g(p,function(b,e){d[b]=a.d(e,"Function")?e():document.getElementById(e)});q&&
q!==document&&g(d,x)!==u;)q=q.parentNode})}}})();(function(){var b=mt.e,a=mt.lang,d=mt.event,k=mt.m;if("undefined"!==typeof h.a&&a.d(c.cvcf,"Array")&&0<c.cvcf.length){var f={Da:function(){for(var a=c.cvcf.length,k,p=0;p<a;p++)(k=b.Wa(decodeURIComponent(c.cvcf[p])))&&d.c(k,"click",f.Sa())},Sa:function(){return function(){h.a.b.et=86;var a={n:"form",t:"clk"};a.id=this.id;h.a.b.ep=k.stringify(a);h.a.h()}}};b.Ab(function(){f.Da()})}})();
(function(){var b=mt.event,a=mt.m;if(c.med&&"undefined"!==typeof h.a){var d=+new Date,k={n:"anti",sb:0,kb:0,clk:0},f=function(){h.a.b.et=86;h.a.b.ep=a.stringify(k);h.a.h()};b.c(document,"click",function(){k.clk++});b.c(document,"keyup",function(){k.kb=1});b.c(window,"scroll",function(){k.sb++});b.c(window,"unload",function(){k.t=+new Date-d;f()});b.c(window,"load",function(){setTimeout(f,5E3)})}})();})();
